### ISSUE TITLE
Create Basic Template For App

### ISSUE THREAD

**Issue by TropicMango** [ucsb-cs56-f18/ucsb-cs56-watch-with-friends#1]
- [x] Have central window for the user to be able to view and watch the video.
- [x] Have button that generates a link for the user to connect to

**Comment by DennisZZH** [comment]
OK. 200 pts.

**Comment by DennisZZH** [comment]
Is the central window page generated by pressing the button? Or are they in the same page? Tell me more about it.
Also, probably more UI widgets are required for the basic template. A central window and button is not quite enough. Please give more detail. Thanks!

**Comment by TropicMango** [comment]
[]- initial window with two options to connect or generate a new room
Once generated window should have:
[] - a viewing area with the video embedded
[] - a button underneath with the option to generate a new link for invites
[] - reserve space for a chat to the side

**Comment by DennisZZH** [comment]
The UI now seems specific enough to be implemented.

**Comment by DennisZZH** [comment]
issue #1 addressed. + 200 pts.
