### ISSUE TITLE
Video -- add button to change the video

### ISSUE THREAD

**Issue by LobinsA** [ucsb-cs56-f18/ucsb-cs56-watch-with-friends#13]
- [x] Retrieve Youtube video url from user via submit form on [WebApp](https://cs56-f18-watch-with-friends.herokuapp.com/)
- [x] In the viewing area, display the desired video.

**Comment by DennisZZH** [comment]
ok. 300 pts

**Comment by DennisZZH** [comment]
issue addressed. + 300 pts
