### ISSUE TITLE
Deploy app on Heroku

### ISSUE THREAD

**Issue by santhameena13** [ucsb-cs56-f18/ucsb-cs56-watch-with-friends#6]
Have a version of the app up and running on Heroku and put a link to that in the README.

**Comment by DennisZZH** [comment]
when you have your app running and deployed on Heroku, please put a link to that in the README.md of your forked repo, thanks.

**Comment by LobinsA** [comment]
Link to Forked Repo: [https://github.com/ucsb-cs56-f18/ucsb-cs56-watch-with-friends](https://github.com/ucsb-cs56-f18/ucsb-cs56-watch-with-friends)
Link to Deployed App: [Watch With Friends](https://cs56-f18-watch-with-friends.herokuapp.com/)

**Comment by DennisZZH** [comment]
issue #6 addressed. + 100 pts.
