### ISSUE TITLE
Create Hash Function 

### ISSUE THREAD

**Issue by LobinsA** [ucsb-cs56-f18/ucsb-cs56-watch-with-friends#7]
- [x] Retrieve a user name and video name from watchwithfriends webapp.
- [x] Create function to sum the ascii values of the input Strings and return a unique number to be used as the code for each session.

**Comment by DennisZZH** [comment]
ok. We've talked about this. 100 pts.

**Comment by DennisZZH** [comment]
issue #7 addressed. + 100 pts.
